version: "2"
# Options for analysis running.
exclude-dirs:
  - certs
  - database
  - load_testing
  - swagger
  - file
  - static

run:
  allow-parallel-runners: true
  timeout: 5m
  tests: true
  modules-download-mode: readonly
