# Options for analysis running.
run:
  skip-dirs:
    - certs
    - database
    - load_testing
    - swagger
  allow-parallel-runners: false
  allow-serial-runners: true
  print-resources-usage: true
