output   = "orm"
wipe     = true
no-tests = true
pkgname  = "orm"

[psql]
  dbname = "burmese_jewellery"
  user = "postgres"
  pass = "postgres"
  host = "localhost"
  port = 5432
  sslmode = "disable"