output   = "orm"
wipe     = true
no-tests = true
pkgname  = "orm"
add-global-variants = true
add-enum-types = true
no-back-referencing = true
add-soft-deletes = true
struct-tag-casing = "camel"

[psql]
  dbname = "burmese_jewellery"
  user = "postgres"
  pass = "postgres"
  host = "localhost"
  port = 5432
  sslmode = "disable"
