openapi: 3.0.2
info:
  title: Burmese Jewellery
  description: API documentaion for Burmese Jewellery.
  version: 1.0.0

externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

servers:
  - url: http://localhost:8077
    description: Local environment

tags:
  - name: admin
    description: Admin
  - name: app
    description: App
  - name: others
    description: Others

paths:
  $ref: ./paths.yml

components:
  $ref: ./components/index.yml
