openapi: 3.0.2
info:
  title: Kikumemo API
  description: API For Kikumemo.
  version: 1.0.0

externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

servers:
  - url: https://api.kikumemo.nouslagus.com
    description: プロダクション環境
  - url: https://api.stg.kikumemo.nouslagus.com
    description: ステージング環境
  - url: https://api.dev.kikumemo.nouslagus.com
    description: デベロッパー環境
  - url: http://api.local.kikumemo.nouslagus.com:8081
    description: ローカル環境
  - url: http://localhost:8081
    description: ローカル環境

tags:
  - name: system_admin
    description: システム管理者のみ使用できるエンドポイント
  - name: operator
    description: operatorとシステム管理者が使用できるエンドポイント
  - name: backlog
    description: 未実装のエンドポイント
  - name: etc
    description: その他

paths:
  $ref: ./paths.yml

components:
  $ref: ./components/index.yml
