openapi: 3.0.2
info:
  title: Burmese Jewellery
  description: API documentaion for Burmese Jewellery.
  version: 1.0.0

externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

servers:
  - url: http://localhost:8077
    description: Local environment

tags:
  - name: admin
    description: Admin
  - name: app
    description: App
  - name: others
    description: Others
  - name: account_admin
    description: Admin Account
  - name: account
    description: Account
  - name: jewellery
    description: Jewellery
  - name: category
    description: Category
  - name: gem
    description: Gem
  - name: material
    description: Material
  - name: faq
    description: Frequently Asked Question
  - name: file
    description: File
  - name: auth
    description: Auth
  - name: profile
    description: Account Profile
  - name: cart
    description: Cart
  - name: favourite
    description: Favourite
  - name: order
    description: Order

paths:
  $ref: ./paths.yml

components:
  $ref: ./components/index.yml
