openapi: 3.0.2
info:
  title: Kikumemo API
  description: API For Kikumemo.
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8077
    description: Local environment
tags:
  - name: admin
    description: Admin
  - name: app
    description: App
  - name: others
    description: Others
paths:
  /api:
    get:
      tags:
        - app
      summary: Display the main page
      responses:
        200:
          description: Main page displayed successfully
  /api/health_check:
    get:
      tags:
        - others
      summary: Health Check
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    default: OK
                required:
                  - message
  /api/auth/google/login:
    get:
      tags:
        - app
      summary: Initiate Google OAuth2 login
      responses:
        302:
          description: Redirect to Google OAuth2 login page
  /api/auth/google/callback:
    get:
      tags:
        - app
      summary: Handle Google OAuth2 callback
      parameters:
        - name: state
          in: query
          required: true
          schema:
            type: string
          description: OAuth2 state parameter
        - name: code
          in: query
          required: true
          schema:
            type: string
          description: OAuth2 code parameter
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthGoogleCallbackResp'
  /api/admin/login:
    post:
      summary: Login as admin user
      tags:
        - admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountAdminLoginParam'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /api/admin/account_admin:
    get:
      summary: List admin user
      tags:
        - admin
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountAdmin'
    post:
      tags:
        - admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountAdminPostParam'
      responses:
        200:
          description: OK
  /api/admin/account_admin/{account_admins_id}:
    get:
      summary: Get admin user
      tags:
        - admin
      parameters:
        - in: path
          name: account_admins_id
          required: true
          schema:
            $ref: '#/components/schemas/ID'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountAdmin'
    put:
      summary: Edit admin user
      tags:
        - admin
      parameters:
        - in: path
          name: account_admins_id
          required: true
          schema:
            $ref: '#/components/schemas/ID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountAdminPutParam'
      responses:
        200:
          description: OK
    delete:
      summary: Delete admin user
      tags:
        - admin
      parameters:
        - in: path
          name: account_admins_id
          required: true
          schema:
            $ref: '#/components/schemas/ID'
      responses:
        204:
          description: Deleted
  /api/admin/account:
    get:
      summary: List user
      tags:
        - admin
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
  /api/admin/account/{account_id}:
    get:
      summary: Get user
      tags:
        - admin
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/ID'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
    put:
      summary: Update user status
      tags:
        - admin
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/ID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountStatusPutParam'
      responses:
        200:
          description: OK
  /api/jewellery:
    get:
      tags:
        - app
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          required: true
          default: 0
        - in: query
          name: limit
          schema:
            type: integer
          required: true
          default: 30
        - in: query
          name: id
          schema:
            $ref: '#/components/schemas/ID'
        - in: query
          name: category_id
          schema:
            $ref: '#/components/schemas/ID'
        - in: query
          name: gem_id
          schema:
            $ref: '#/components/schemas/ID'
        - in: query
          name: material_id
          schema:
            $ref: '#/components/schemas/ID'
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: is_published
          schema:
            type: boolean
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Jewellery'
  /api/jewellery/{jewellery_id}:
    get:
      tags:
        - app
      parameters:
        - in: path
          name: jewellery_id
          required: true
          schema:
            $ref: '#/components/schemas/ID'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jewellery'
  /api/admin/jewellery:
    post:
      tags:
        - admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JewelleryPostParam'
      responses:
        200:
          description: OK
  /api/admin/jewellery/{jewellery_id}:
    put:
      tags:
        - admin
      parameters:
        - in: path
          name: jewellery_id
          required: true
          schema:
            $ref: '#/components/schemas/ID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JewelleryPutParam'
      responses:
        200:
          description: OK
components:
  parameters: null
  schemas:
    AuthGoogleCallbackResp:
      type: object
      properties:
        account:
          $ref: '#/components/schemas/Account'
        is_registered:
          type: boolean
          example: true
      required:
        - is_registered
    ErrMsg:
      description: Error Message
      properties:
        version:
          type: string
          description: Application Version
        message:
          type: string
          description: Error message
    ID:
      type: string
      format: uuid
    AccountAdmin:
      type: object
      properties:
        account_admin_id:
          type: string
          format: uuid
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        mail:
          type: string
          maxLength: 255
          format: email
          example: test@gmail.com
        account_admin_role:
          type: string
          maxLength: 255
          example: staff
          enum:
            - admin
            - staff
        account_admin_status:
          type: string
          maxLength: 255
          enum:
            - active
            - locked
            - deactivated
          example: active
        created_at:
          type: string
          format: date-time
          example: 2020-01-01 00:00:00+00:00
        updated_at:
          type: string
          format: date-time
          example: 2020-01-01 00:00:00+00:00
      required:
        - account_admin_id
        - mail
        - account_admin_role
        - account_admin_status
        - created_at
        - updated_at
    AccountAdminLoginParam:
      type: object
      properties:
        mail:
          type: string
          maxLength: 255
          format: email
          example: test@gmail.com
        password:
          type: string
          maxLength: 255
          example: '*****'
      required:
        - mail
        - password
    AccountAdminPostParam:
      type: object
      properties:
        mail:
          type: string
          maxLength: 255
          format: email
          example: test@gmail.com
        password:
          type: string
          maxLength: 255
          example: '*****'
        account_admin_role:
          type: string
          maxLength: 255
          example: staff
          enum:
            - admin
            - staff
        account_admin_status:
          type: string
          maxLength: 255
          enum:
            - active
            - locked
            - deactivated
          example: active
      required:
        - mail
        - password
        - account_admin_role
        - account_admin_status
    AccountAdminPutParam:
      type: object
      properties:
        password:
          type: string
          maxLength: 255
          example: '*****'
        account_admin_role:
          type: string
          maxLength: 255
          example: staff
          enum:
            - admin
            - staff
        account_admin_status:
          type: string
          maxLength: 255
          enum:
            - active
            - locked
            - deactivated
          example: active
    Account:
      type: object
      properties:
        account_id:
          type: string
          format: uuid
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        login_type:
          type: string
          maxLength: 255
          example: email
          enum:
            - email
            - phone
            - google
            - facebook
        login_id:
          type: string
          maxLength: 255
          example: 101176734510758999999
        mail:
          type: string
          maxLength: 255
          format: email
          example: test@gmail.com
        phone:
          type: string
          maxLength: 255
          example: 08088889999
        account_status:
          type: string
          maxLength: 255
          example: active
          enum:
            - pending
            - active
            - locked
            - deactivated
        created_at:
          type: string
          format: date-time
          example: 2020-01-01 00:00:00+00:00
        updated_at:
          type: string
          format: date-time
          example: 2020-01-01 00:00:00+00:00
      required:
        - account_id
        - login_type
        - account_status
        - created_at
        - updated_at
    AccountStatusPutParam:
      type: object
      properties:
        account_status:
          type: string
          maxLength: 255
          example: active
          enum:
            - pending
            - active
            - locked
            - deactivated
      required:
        - account_status
    Jewellery:
      type: object
      properties:
        jewellery_id:
          type: string
          format: uuid
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        category_id:
          type: string
          format: uuid
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        gem_id:
          type: string
          format: uuid
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        material_id:
          type: string
          format: uuid
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        name:
          type: string
          maxLength: 255
          example: Wedding Forever
        description:
          type: string
          maxLength: 255
          example: Wedding Forever in Platinum with a Half-circle of Diamonds, 2.2
            mm
        quantity:
          type: integer
          format: int64
          example: 100
        price:
          type: integer
          format: float64
          example: 10000
        image_url:
          type: string
          example: https://media.tiffany.com/is/image/Tiffany/EcomItemL2/tiffany-foreverband-ring-16574635_1045538_ED_M.jpg?&op_usm=1.75,1.0,6.0&$cropN=0.1,0.1,0.8,0.8&defaultImage=NoImageAvailableInternal&&defaultImage=NoImageAvailableInternal&fmt=webp
        is_published:
          type: boolean
          example: true
        created_at:
          type: string
          format: date-time
          example: 2020-01-01 00:00:00+00:00
        updated_at:
          type: string
          format: date-time
          example: 2020-01-01 00:00:00+00:00
      required:
        - jewellery_id
        - category_id
        - gem_id
        - material_id
        - name
        - description
        - quantity
        - price
        - image_url
        - is_published
        - created_at
        - updated_at
    JewelleryPostParam:
      type: object
      properties:
        jewellery_id:
          type: string
          format: uuid
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        category_id:
          type: string
          format: uuid
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        gem_id:
          type: string
          format: uuid
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        material_id:
          type: string
          format: uuid
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        name:
          type: string
          maxLength: 255
          example: Wedding Forever
        description:
          type: string
          maxLength: 255
          example: Wedding Forever in Platinum with a Half-circle of Diamonds, 2.2
            mm
        quantity:
          type: integer
          format: int64
          example: 100
        price:
          type: integer
          format: float64
          example: 10000
        image_url:
          type: string
          example: https://media.tiffany.com/is/image/Tiffany/EcomItemL2/tiffany-foreverband-ring-16574635_1045538_ED_M.jpg?&op_usm=1.75,1.0,6.0&$cropN=0.1,0.1,0.8,0.8&defaultImage=NoImageAvailableInternal&&defaultImage=NoImageAvailableInternal&fmt=webp
        is_published:
          type: boolean
          example: true
      required:
        - jewellery_id
        - category_id
        - gem_id
        - material_id
        - name
        - description
        - quantity
        - price
        - image_url
        - is_published
    JewelleryPutParam:
      type: object
      properties:
        category_id:
          type: string
          format: uuid
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        gem_id:
          type: string
          format: uuid
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        material_id:
          type: string
          format: uuid
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        name:
          type: string
          maxLength: 255
          example: Wedding Forever
        description:
          type: string
          maxLength: 255
          example: Wedding Forever in Platinum with a Half-circle of Diamonds, 2.2
            mm
        quantity:
          type: integer
          format: int64
          example: 100
        price:
          type: integer
          format: float64
          example: 10000
        image_url:
          type: string
          example: https://media.tiffany.com/is/image/Tiffany/EcomItemL2/tiffany-foreverband-ring-16574635_1045538_ED_M.jpg?&op_usm=1.75,1.0,6.0&$cropN=0.1,0.1,0.8,0.8&defaultImage=NoImageAvailableInternal&&defaultImage=NoImageAvailableInternal&fmt=webp
        is_published:
          type: boolean
          example: true
      required:
        - category_id
        - gem_id
        - material_id
        - name
        - description
        - quantity
        - price
        - image_url
        - is_published
