// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// AccountFavourite is an object representing the database table.
type AccountFavourite struct {
	AccountID   string    `boil:"account_id" json:"accountID" toml:"accountID" yaml:"accountID"`
	JewelleryID string    `boil:"jewellery_id" json:"jewelleryID" toml:"jewelleryID" yaml:"jewelleryID"`
	CreatedAt   time.Time `boil:"created_at" json:"createdAt" toml:"createdAt" yaml:"createdAt"`
	UpdatedAt   time.Time `boil:"updated_at" json:"updatedAt" toml:"updatedAt" yaml:"updatedAt"`

	R *accountFavouriteR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L accountFavouriteL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AccountFavouriteColumns = struct {
	AccountID   string
	JewelleryID string
	CreatedAt   string
	UpdatedAt   string
}{
	AccountID:   "account_id",
	JewelleryID: "jewellery_id",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

var AccountFavouriteTableColumns = struct {
	AccountID   string
	JewelleryID string
	CreatedAt   string
	UpdatedAt   string
}{
	AccountID:   "account_favourites.account_id",
	JewelleryID: "account_favourites.jewellery_id",
	CreatedAt:   "account_favourites.created_at",
	UpdatedAt:   "account_favourites.updated_at",
}

// Generated where

var AccountFavouriteWhere = struct {
	AccountID   whereHelperstring
	JewelleryID whereHelperstring
	CreatedAt   whereHelpertime_Time
	UpdatedAt   whereHelpertime_Time
}{
	AccountID:   whereHelperstring{field: "\"account_favourites\".\"account_id\""},
	JewelleryID: whereHelperstring{field: "\"account_favourites\".\"jewellery_id\""},
	CreatedAt:   whereHelpertime_Time{field: "\"account_favourites\".\"created_at\""},
	UpdatedAt:   whereHelpertime_Time{field: "\"account_favourites\".\"updated_at\""},
}

// AccountFavouriteRels is where relationship names are stored.
var AccountFavouriteRels = struct {
	Account   string
	Jewellery string
}{
	Account:   "Account",
	Jewellery: "Jewellery",
}

// accountFavouriteR is where relationships are stored.
type accountFavouriteR struct {
	Account   *Account   `boil:"Account" json:"Account" toml:"Account" yaml:"Account"`
	Jewellery *Jewellery `boil:"Jewellery" json:"Jewellery" toml:"Jewellery" yaml:"Jewellery"`
}

// NewStruct creates a new relationship struct
func (*accountFavouriteR) NewStruct() *accountFavouriteR {
	return &accountFavouriteR{}
}

func (r *accountFavouriteR) GetAccount() *Account {
	if r == nil {
		return nil
	}
	return r.Account
}

func (r *accountFavouriteR) GetJewellery() *Jewellery {
	if r == nil {
		return nil
	}
	return r.Jewellery
}

// accountFavouriteL is where Load methods for each relationship are stored.
type accountFavouriteL struct{}

var (
	accountFavouriteAllColumns            = []string{"account_id", "jewellery_id", "created_at", "updated_at"}
	accountFavouriteColumnsWithoutDefault = []string{"account_id", "jewellery_id"}
	accountFavouriteColumnsWithDefault    = []string{"created_at", "updated_at"}
	accountFavouritePrimaryKeyColumns     = []string{"account_id", "jewellery_id"}
	accountFavouriteGeneratedColumns      = []string{}
)

type (
	// AccountFavouriteSlice is an alias for a slice of pointers to AccountFavourite.
	// This should almost always be used instead of []AccountFavourite.
	AccountFavouriteSlice []*AccountFavourite
	// AccountFavouriteHook is the signature for custom AccountFavourite hook methods
	AccountFavouriteHook func(context.Context, boil.ContextExecutor, *AccountFavourite) error

	accountFavouriteQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	accountFavouriteType                 = reflect.TypeOf(&AccountFavourite{})
	accountFavouriteMapping              = queries.MakeStructMapping(accountFavouriteType)
	accountFavouritePrimaryKeyMapping, _ = queries.BindMapping(accountFavouriteType, accountFavouriteMapping, accountFavouritePrimaryKeyColumns)
	accountFavouriteInsertCacheMut       sync.RWMutex
	accountFavouriteInsertCache          = make(map[string]insertCache)
	accountFavouriteUpdateCacheMut       sync.RWMutex
	accountFavouriteUpdateCache          = make(map[string]updateCache)
	accountFavouriteUpsertCacheMut       sync.RWMutex
	accountFavouriteUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var accountFavouriteAfterSelectHooks []AccountFavouriteHook

var accountFavouriteBeforeInsertHooks []AccountFavouriteHook
var accountFavouriteAfterInsertHooks []AccountFavouriteHook

var accountFavouriteBeforeUpdateHooks []AccountFavouriteHook
var accountFavouriteAfterUpdateHooks []AccountFavouriteHook

var accountFavouriteBeforeDeleteHooks []AccountFavouriteHook
var accountFavouriteAfterDeleteHooks []AccountFavouriteHook

var accountFavouriteBeforeUpsertHooks []AccountFavouriteHook
var accountFavouriteAfterUpsertHooks []AccountFavouriteHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AccountFavourite) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountFavouriteAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AccountFavourite) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountFavouriteBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AccountFavourite) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountFavouriteAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AccountFavourite) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountFavouriteBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AccountFavourite) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountFavouriteAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AccountFavourite) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountFavouriteBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AccountFavourite) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountFavouriteAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AccountFavourite) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountFavouriteBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AccountFavourite) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountFavouriteAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAccountFavouriteHook registers your hook function for all future operations.
func AddAccountFavouriteHook(hookPoint boil.HookPoint, accountFavouriteHook AccountFavouriteHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		accountFavouriteAfterSelectHooks = append(accountFavouriteAfterSelectHooks, accountFavouriteHook)
	case boil.BeforeInsertHook:
		accountFavouriteBeforeInsertHooks = append(accountFavouriteBeforeInsertHooks, accountFavouriteHook)
	case boil.AfterInsertHook:
		accountFavouriteAfterInsertHooks = append(accountFavouriteAfterInsertHooks, accountFavouriteHook)
	case boil.BeforeUpdateHook:
		accountFavouriteBeforeUpdateHooks = append(accountFavouriteBeforeUpdateHooks, accountFavouriteHook)
	case boil.AfterUpdateHook:
		accountFavouriteAfterUpdateHooks = append(accountFavouriteAfterUpdateHooks, accountFavouriteHook)
	case boil.BeforeDeleteHook:
		accountFavouriteBeforeDeleteHooks = append(accountFavouriteBeforeDeleteHooks, accountFavouriteHook)
	case boil.AfterDeleteHook:
		accountFavouriteAfterDeleteHooks = append(accountFavouriteAfterDeleteHooks, accountFavouriteHook)
	case boil.BeforeUpsertHook:
		accountFavouriteBeforeUpsertHooks = append(accountFavouriteBeforeUpsertHooks, accountFavouriteHook)
	case boil.AfterUpsertHook:
		accountFavouriteAfterUpsertHooks = append(accountFavouriteAfterUpsertHooks, accountFavouriteHook)
	}
}

// OneG returns a single accountFavourite record from the query using the global executor.
func (q accountFavouriteQuery) OneG(ctx context.Context) (*AccountFavourite, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single accountFavourite record from the query.
func (q accountFavouriteQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AccountFavourite, error) {
	o := &AccountFavourite{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "orm: failed to execute a one query for account_favourites")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all AccountFavourite records from the query using the global executor.
func (q accountFavouriteQuery) AllG(ctx context.Context) (AccountFavouriteSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all AccountFavourite records from the query.
func (q accountFavouriteQuery) All(ctx context.Context, exec boil.ContextExecutor) (AccountFavouriteSlice, error) {
	var o []*AccountFavourite

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "orm: failed to assign all query results to AccountFavourite slice")
	}

	if len(accountFavouriteAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all AccountFavourite records in the query using the global executor
func (q accountFavouriteQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all AccountFavourite records in the query.
func (q accountFavouriteQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to count account_favourites rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q accountFavouriteQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q accountFavouriteQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "orm: failed to check if account_favourites exists")
	}

	return count > 0, nil
}

// Account pointed to by the foreign key.
func (o *AccountFavourite) Account(mods ...qm.QueryMod) accountQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"account_id\" = ?", o.AccountID),
	}

	queryMods = append(queryMods, mods...)

	return Accounts(queryMods...)
}

// Jewellery pointed to by the foreign key.
func (o *AccountFavourite) Jewellery(mods ...qm.QueryMod) jewelleryQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"jewellery_id\" = ?", o.JewelleryID),
	}

	queryMods = append(queryMods, mods...)

	return Jewelleries(queryMods...)
}

// LoadAccount allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (accountFavouriteL) LoadAccount(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAccountFavourite interface{}, mods queries.Applicator) error {
	var slice []*AccountFavourite
	var object *AccountFavourite

	if singular {
		var ok bool
		object, ok = maybeAccountFavourite.(*AccountFavourite)
		if !ok {
			object = new(AccountFavourite)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAccountFavourite)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAccountFavourite))
			}
		}
	} else {
		s, ok := maybeAccountFavourite.(*[]*AccountFavourite)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAccountFavourite)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAccountFavourite))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &accountFavouriteR{}
		}
		args = append(args, object.AccountID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &accountFavouriteR{}
			}

			for _, a := range args {
				if a == obj.AccountID {
					continue Outer
				}
			}

			args = append(args, obj.AccountID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`accounts`),
		qm.WhereIn(`accounts.account_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Account")
	}

	var resultSlice []*Account
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Account")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for accounts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for accounts")
	}

	if len(accountAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Account = foreign
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.AccountID == foreign.AccountID {
				local.R.Account = foreign
				break
			}
		}
	}

	return nil
}

// LoadJewellery allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (accountFavouriteL) LoadJewellery(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAccountFavourite interface{}, mods queries.Applicator) error {
	var slice []*AccountFavourite
	var object *AccountFavourite

	if singular {
		var ok bool
		object, ok = maybeAccountFavourite.(*AccountFavourite)
		if !ok {
			object = new(AccountFavourite)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAccountFavourite)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAccountFavourite))
			}
		}
	} else {
		s, ok := maybeAccountFavourite.(*[]*AccountFavourite)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAccountFavourite)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAccountFavourite))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &accountFavouriteR{}
		}
		args = append(args, object.JewelleryID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &accountFavouriteR{}
			}

			for _, a := range args {
				if a == obj.JewelleryID {
					continue Outer
				}
			}

			args = append(args, obj.JewelleryID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`jewelleries`),
		qm.WhereIn(`jewelleries.jewellery_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Jewellery")
	}

	var resultSlice []*Jewellery
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Jewellery")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for jewelleries")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for jewelleries")
	}

	if len(jewelleryAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Jewellery = foreign
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.JewelleryID == foreign.JewelleryID {
				local.R.Jewellery = foreign
				break
			}
		}
	}

	return nil
}

// SetAccountG of the accountFavourite to the related item.
// Sets o.R.Account to related.
// Uses the global database handle.
func (o *AccountFavourite) SetAccountG(ctx context.Context, insert bool, related *Account) error {
	return o.SetAccount(ctx, boil.GetContextDB(), insert, related)
}

// SetAccount of the accountFavourite to the related item.
// Sets o.R.Account to related.
func (o *AccountFavourite) SetAccount(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Account) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"account_favourites\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"account_id"}),
		strmangle.WhereClause("\"", "\"", 2, accountFavouritePrimaryKeyColumns),
	)
	values := []interface{}{related.AccountID, o.AccountID, o.JewelleryID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.AccountID = related.AccountID
	if o.R == nil {
		o.R = &accountFavouriteR{
			Account: related,
		}
	} else {
		o.R.Account = related
	}

	return nil
}

// SetJewelleryG of the accountFavourite to the related item.
// Sets o.R.Jewellery to related.
// Uses the global database handle.
func (o *AccountFavourite) SetJewelleryG(ctx context.Context, insert bool, related *Jewellery) error {
	return o.SetJewellery(ctx, boil.GetContextDB(), insert, related)
}

// SetJewellery of the accountFavourite to the related item.
// Sets o.R.Jewellery to related.
func (o *AccountFavourite) SetJewellery(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Jewellery) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"account_favourites\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"jewellery_id"}),
		strmangle.WhereClause("\"", "\"", 2, accountFavouritePrimaryKeyColumns),
	)
	values := []interface{}{related.JewelleryID, o.AccountID, o.JewelleryID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.JewelleryID = related.JewelleryID
	if o.R == nil {
		o.R = &accountFavouriteR{
			Jewellery: related,
		}
	} else {
		o.R.Jewellery = related
	}

	return nil
}

// AccountFavourites retrieves all the records using an executor.
func AccountFavourites(mods ...qm.QueryMod) accountFavouriteQuery {
	mods = append(mods, qm.From("\"account_favourites\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"account_favourites\".*"})
	}

	return accountFavouriteQuery{q}
}

// FindAccountFavouriteG retrieves a single record by ID.
func FindAccountFavouriteG(ctx context.Context, accountID string, jewelleryID string, selectCols ...string) (*AccountFavourite, error) {
	return FindAccountFavourite(ctx, boil.GetContextDB(), accountID, jewelleryID, selectCols...)
}

// FindAccountFavourite retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAccountFavourite(ctx context.Context, exec boil.ContextExecutor, accountID string, jewelleryID string, selectCols ...string) (*AccountFavourite, error) {
	accountFavouriteObj := &AccountFavourite{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"account_favourites\" where \"account_id\"=$1 AND \"jewellery_id\"=$2", sel,
	)

	q := queries.Raw(query, accountID, jewelleryID)

	err := q.Bind(ctx, exec, accountFavouriteObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "orm: unable to select from account_favourites")
	}

	if err = accountFavouriteObj.doAfterSelectHooks(ctx, exec); err != nil {
		return accountFavouriteObj, err
	}

	return accountFavouriteObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *AccountFavourite) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AccountFavourite) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("orm: no account_favourites provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accountFavouriteColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	accountFavouriteInsertCacheMut.RLock()
	cache, cached := accountFavouriteInsertCache[key]
	accountFavouriteInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			accountFavouriteAllColumns,
			accountFavouriteColumnsWithDefault,
			accountFavouriteColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(accountFavouriteType, accountFavouriteMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(accountFavouriteType, accountFavouriteMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"account_favourites\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"account_favourites\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "orm: unable to insert into account_favourites")
	}

	if !cached {
		accountFavouriteInsertCacheMut.Lock()
		accountFavouriteInsertCache[key] = cache
		accountFavouriteInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single AccountFavourite record using the global executor.
// See Update for more documentation.
func (o *AccountFavourite) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the AccountFavourite.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AccountFavourite) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	accountFavouriteUpdateCacheMut.RLock()
	cache, cached := accountFavouriteUpdateCache[key]
	accountFavouriteUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			accountFavouriteAllColumns,
			accountFavouritePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("orm: unable to update account_favourites, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"account_favourites\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, accountFavouritePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(accountFavouriteType, accountFavouriteMapping, append(wl, accountFavouritePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update account_favourites row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by update for account_favourites")
	}

	if !cached {
		accountFavouriteUpdateCacheMut.Lock()
		accountFavouriteUpdateCache[key] = cache
		accountFavouriteUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q accountFavouriteQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q accountFavouriteQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update all for account_favourites")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to retrieve rows affected for account_favourites")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o AccountFavouriteSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AccountFavouriteSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("orm: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountFavouritePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"account_favourites\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, accountFavouritePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update all in accountFavourite slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to retrieve rows affected all in update all accountFavourite")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *AccountFavourite) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AccountFavourite) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("orm: no account_favourites provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accountFavouriteColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	accountFavouriteUpsertCacheMut.RLock()
	cache, cached := accountFavouriteUpsertCache[key]
	accountFavouriteUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			accountFavouriteAllColumns,
			accountFavouriteColumnsWithDefault,
			accountFavouriteColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			accountFavouriteAllColumns,
			accountFavouritePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("orm: unable to upsert account_favourites, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(accountFavouritePrimaryKeyColumns))
			copy(conflict, accountFavouritePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"account_favourites\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(accountFavouriteType, accountFavouriteMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(accountFavouriteType, accountFavouriteMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "orm: unable to upsert account_favourites")
	}

	if !cached {
		accountFavouriteUpsertCacheMut.Lock()
		accountFavouriteUpsertCache[key] = cache
		accountFavouriteUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single AccountFavourite record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *AccountFavourite) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single AccountFavourite record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AccountFavourite) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("orm: no AccountFavourite provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), accountFavouritePrimaryKeyMapping)
	sql := "DELETE FROM \"account_favourites\" WHERE \"account_id\"=$1 AND \"jewellery_id\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete from account_favourites")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by delete for account_favourites")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q accountFavouriteQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q accountFavouriteQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("orm: no accountFavouriteQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete all from account_favourites")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by deleteall for account_favourites")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o AccountFavouriteSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AccountFavouriteSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(accountFavouriteBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountFavouritePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"account_favourites\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountFavouritePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete all from accountFavourite slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by deleteall for account_favourites")
	}

	if len(accountFavouriteAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *AccountFavourite) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("orm: no AccountFavourite provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AccountFavourite) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAccountFavourite(ctx, exec, o.AccountID, o.JewelleryID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AccountFavouriteSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("orm: empty AccountFavouriteSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AccountFavouriteSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AccountFavouriteSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountFavouritePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"account_favourites\".* FROM \"account_favourites\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountFavouritePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "orm: unable to reload all in AccountFavouriteSlice")
	}

	*o = slice

	return nil
}

// AccountFavouriteExistsG checks if the AccountFavourite row exists.
func AccountFavouriteExistsG(ctx context.Context, accountID string, jewelleryID string) (bool, error) {
	return AccountFavouriteExists(ctx, boil.GetContextDB(), accountID, jewelleryID)
}

// AccountFavouriteExists checks if the AccountFavourite row exists.
func AccountFavouriteExists(ctx context.Context, exec boil.ContextExecutor, accountID string, jewelleryID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"account_favourites\" where \"account_id\"=$1 AND \"jewellery_id\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, accountID, jewelleryID)
	}
	row := exec.QueryRowContext(ctx, sql, accountID, jewelleryID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "orm: unable to check if account_favourites exists")
	}

	return exists, nil
}

// Exists checks if the AccountFavourite row exists.
func (o *AccountFavourite) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AccountFavouriteExists(ctx, exec, o.AccountID, o.JewelleryID)
}
