// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// AccountCart is an object representing the database table.
type AccountCart struct {
	CartID    string    `boil:"cart_id" json:"cartID" toml:"cartID" yaml:"cartID"`
	AccountID string    `boil:"account_id" json:"accountID" toml:"accountID" yaml:"accountID"`
	CreatedAt time.Time `boil:"created_at" json:"createdAt" toml:"createdAt" yaml:"createdAt"`
	UpdatedAt time.Time `boil:"updated_at" json:"updatedAt" toml:"updatedAt" yaml:"updatedAt"`

	R *accountCartR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L accountCartL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AccountCartColumns = struct {
	CartID    string
	AccountID string
	CreatedAt string
	UpdatedAt string
}{
	CartID:    "cart_id",
	AccountID: "account_id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var AccountCartTableColumns = struct {
	CartID    string
	AccountID string
	CreatedAt string
	UpdatedAt string
}{
	CartID:    "account_carts.cart_id",
	AccountID: "account_carts.account_id",
	CreatedAt: "account_carts.created_at",
	UpdatedAt: "account_carts.updated_at",
}

// Generated where

var AccountCartWhere = struct {
	CartID    whereHelperstring
	AccountID whereHelperstring
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	CartID:    whereHelperstring{field: "\"account_carts\".\"cart_id\""},
	AccountID: whereHelperstring{field: "\"account_carts\".\"account_id\""},
	CreatedAt: whereHelpertime_Time{field: "\"account_carts\".\"created_at\""},
	UpdatedAt: whereHelpertime_Time{field: "\"account_carts\".\"updated_at\""},
}

// AccountCartRels is where relationship names are stored.
var AccountCartRels = struct {
	Account                    string
	CartAccountCartJewelleries string
}{
	Account:                    "Account",
	CartAccountCartJewelleries: "CartAccountCartJewelleries",
}

// accountCartR is where relationships are stored.
type accountCartR struct {
	Account                    *Account                  `boil:"Account" json:"Account" toml:"Account" yaml:"Account"`
	CartAccountCartJewelleries AccountCartJewellerySlice `boil:"CartAccountCartJewelleries" json:"CartAccountCartJewelleries" toml:"CartAccountCartJewelleries" yaml:"CartAccountCartJewelleries"`
}

// NewStruct creates a new relationship struct
func (*accountCartR) NewStruct() *accountCartR {
	return &accountCartR{}
}

func (r *accountCartR) GetAccount() *Account {
	if r == nil {
		return nil
	}
	return r.Account
}

func (r *accountCartR) GetCartAccountCartJewelleries() AccountCartJewellerySlice {
	if r == nil {
		return nil
	}
	return r.CartAccountCartJewelleries
}

// accountCartL is where Load methods for each relationship are stored.
type accountCartL struct{}

var (
	accountCartAllColumns            = []string{"cart_id", "account_id", "created_at", "updated_at"}
	accountCartColumnsWithoutDefault = []string{"account_id"}
	accountCartColumnsWithDefault    = []string{"cart_id", "created_at", "updated_at"}
	accountCartPrimaryKeyColumns     = []string{"cart_id"}
	accountCartGeneratedColumns      = []string{}
)

type (
	// AccountCartSlice is an alias for a slice of pointers to AccountCart.
	// This should almost always be used instead of []AccountCart.
	AccountCartSlice []*AccountCart
	// AccountCartHook is the signature for custom AccountCart hook methods
	AccountCartHook func(context.Context, boil.ContextExecutor, *AccountCart) error

	accountCartQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	accountCartType                 = reflect.TypeOf(&AccountCart{})
	accountCartMapping              = queries.MakeStructMapping(accountCartType)
	accountCartPrimaryKeyMapping, _ = queries.BindMapping(accountCartType, accountCartMapping, accountCartPrimaryKeyColumns)
	accountCartInsertCacheMut       sync.RWMutex
	accountCartInsertCache          = make(map[string]insertCache)
	accountCartUpdateCacheMut       sync.RWMutex
	accountCartUpdateCache          = make(map[string]updateCache)
	accountCartUpsertCacheMut       sync.RWMutex
	accountCartUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var accountCartAfterSelectHooks []AccountCartHook

var accountCartBeforeInsertHooks []AccountCartHook
var accountCartAfterInsertHooks []AccountCartHook

var accountCartBeforeUpdateHooks []AccountCartHook
var accountCartAfterUpdateHooks []AccountCartHook

var accountCartBeforeDeleteHooks []AccountCartHook
var accountCartAfterDeleteHooks []AccountCartHook

var accountCartBeforeUpsertHooks []AccountCartHook
var accountCartAfterUpsertHooks []AccountCartHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AccountCart) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountCartAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AccountCart) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountCartBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AccountCart) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountCartAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AccountCart) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountCartBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AccountCart) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountCartAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AccountCart) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountCartBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AccountCart) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountCartAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AccountCart) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountCartBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AccountCart) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountCartAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAccountCartHook registers your hook function for all future operations.
func AddAccountCartHook(hookPoint boil.HookPoint, accountCartHook AccountCartHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		accountCartAfterSelectHooks = append(accountCartAfterSelectHooks, accountCartHook)
	case boil.BeforeInsertHook:
		accountCartBeforeInsertHooks = append(accountCartBeforeInsertHooks, accountCartHook)
	case boil.AfterInsertHook:
		accountCartAfterInsertHooks = append(accountCartAfterInsertHooks, accountCartHook)
	case boil.BeforeUpdateHook:
		accountCartBeforeUpdateHooks = append(accountCartBeforeUpdateHooks, accountCartHook)
	case boil.AfterUpdateHook:
		accountCartAfterUpdateHooks = append(accountCartAfterUpdateHooks, accountCartHook)
	case boil.BeforeDeleteHook:
		accountCartBeforeDeleteHooks = append(accountCartBeforeDeleteHooks, accountCartHook)
	case boil.AfterDeleteHook:
		accountCartAfterDeleteHooks = append(accountCartAfterDeleteHooks, accountCartHook)
	case boil.BeforeUpsertHook:
		accountCartBeforeUpsertHooks = append(accountCartBeforeUpsertHooks, accountCartHook)
	case boil.AfterUpsertHook:
		accountCartAfterUpsertHooks = append(accountCartAfterUpsertHooks, accountCartHook)
	}
}

// OneG returns a single accountCart record from the query using the global executor.
func (q accountCartQuery) OneG(ctx context.Context) (*AccountCart, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single accountCart record from the query.
func (q accountCartQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AccountCart, error) {
	o := &AccountCart{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "orm: failed to execute a one query for account_carts")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all AccountCart records from the query using the global executor.
func (q accountCartQuery) AllG(ctx context.Context) (AccountCartSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all AccountCart records from the query.
func (q accountCartQuery) All(ctx context.Context, exec boil.ContextExecutor) (AccountCartSlice, error) {
	var o []*AccountCart

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "orm: failed to assign all query results to AccountCart slice")
	}

	if len(accountCartAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all AccountCart records in the query using the global executor
func (q accountCartQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all AccountCart records in the query.
func (q accountCartQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to count account_carts rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q accountCartQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q accountCartQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "orm: failed to check if account_carts exists")
	}

	return count > 0, nil
}

// Account pointed to by the foreign key.
func (o *AccountCart) Account(mods ...qm.QueryMod) accountQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"account_id\" = ?", o.AccountID),
	}

	queryMods = append(queryMods, mods...)

	return Accounts(queryMods...)
}

// CartAccountCartJewelleries retrieves all the account_cart_jewellery's AccountCartJewelleries with an executor via cart_id column.
func (o *AccountCart) CartAccountCartJewelleries(mods ...qm.QueryMod) accountCartJewelleryQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"account_cart_jewelleries\".\"cart_id\"=?", o.CartID),
	)

	return AccountCartJewelleries(queryMods...)
}

// LoadAccount allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (accountCartL) LoadAccount(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAccountCart interface{}, mods queries.Applicator) error {
	var slice []*AccountCart
	var object *AccountCart

	if singular {
		var ok bool
		object, ok = maybeAccountCart.(*AccountCart)
		if !ok {
			object = new(AccountCart)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAccountCart)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAccountCart))
			}
		}
	} else {
		s, ok := maybeAccountCart.(*[]*AccountCart)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAccountCart)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAccountCart))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &accountCartR{}
		}
		args = append(args, object.AccountID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &accountCartR{}
			}

			for _, a := range args {
				if a == obj.AccountID {
					continue Outer
				}
			}

			args = append(args, obj.AccountID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`accounts`),
		qm.WhereIn(`accounts.account_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Account")
	}

	var resultSlice []*Account
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Account")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for accounts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for accounts")
	}

	if len(accountAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Account = foreign
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.AccountID == foreign.AccountID {
				local.R.Account = foreign
				break
			}
		}
	}

	return nil
}

// LoadCartAccountCartJewelleries allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (accountCartL) LoadCartAccountCartJewelleries(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAccountCart interface{}, mods queries.Applicator) error {
	var slice []*AccountCart
	var object *AccountCart

	if singular {
		var ok bool
		object, ok = maybeAccountCart.(*AccountCart)
		if !ok {
			object = new(AccountCart)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAccountCart)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAccountCart))
			}
		}
	} else {
		s, ok := maybeAccountCart.(*[]*AccountCart)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAccountCart)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAccountCart))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &accountCartR{}
		}
		args = append(args, object.CartID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &accountCartR{}
			}

			for _, a := range args {
				if a == obj.CartID {
					continue Outer
				}
			}

			args = append(args, obj.CartID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`account_cart_jewelleries`),
		qm.WhereIn(`account_cart_jewelleries.cart_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load account_cart_jewelleries")
	}

	var resultSlice []*AccountCartJewellery
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice account_cart_jewelleries")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on account_cart_jewelleries")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for account_cart_jewelleries")
	}

	if len(accountCartJewelleryAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.CartAccountCartJewelleries = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.CartID == foreign.CartID {
				local.R.CartAccountCartJewelleries = append(local.R.CartAccountCartJewelleries, foreign)
				break
			}
		}
	}

	return nil
}

// SetAccountG of the accountCart to the related item.
// Sets o.R.Account to related.
// Uses the global database handle.
func (o *AccountCart) SetAccountG(ctx context.Context, insert bool, related *Account) error {
	return o.SetAccount(ctx, boil.GetContextDB(), insert, related)
}

// SetAccount of the accountCart to the related item.
// Sets o.R.Account to related.
func (o *AccountCart) SetAccount(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Account) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"account_carts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"account_id"}),
		strmangle.WhereClause("\"", "\"", 2, accountCartPrimaryKeyColumns),
	)
	values := []interface{}{related.AccountID, o.CartID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.AccountID = related.AccountID
	if o.R == nil {
		o.R = &accountCartR{
			Account: related,
		}
	} else {
		o.R.Account = related
	}

	return nil
}

// AddCartAccountCartJewelleriesG adds the given related objects to the existing relationships
// of the account_cart, optionally inserting them as new records.
// Appends related to o.R.CartAccountCartJewelleries.
// Uses the global database handle.
func (o *AccountCart) AddCartAccountCartJewelleriesG(ctx context.Context, insert bool, related ...*AccountCartJewellery) error {
	return o.AddCartAccountCartJewelleries(ctx, boil.GetContextDB(), insert, related...)
}

// AddCartAccountCartJewelleries adds the given related objects to the existing relationships
// of the account_cart, optionally inserting them as new records.
// Appends related to o.R.CartAccountCartJewelleries.
func (o *AccountCart) AddCartAccountCartJewelleries(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*AccountCartJewellery) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.CartID = o.CartID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"account_cart_jewelleries\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"cart_id"}),
				strmangle.WhereClause("\"", "\"", 2, accountCartJewelleryPrimaryKeyColumns),
			)
			values := []interface{}{o.CartID, rel.CartID, rel.JewelleryID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.CartID = o.CartID
		}
	}

	if o.R == nil {
		o.R = &accountCartR{
			CartAccountCartJewelleries: related,
		}
	} else {
		o.R.CartAccountCartJewelleries = append(o.R.CartAccountCartJewelleries, related...)
	}

	return nil
}

// AccountCarts retrieves all the records using an executor.
func AccountCarts(mods ...qm.QueryMod) accountCartQuery {
	mods = append(mods, qm.From("\"account_carts\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"account_carts\".*"})
	}

	return accountCartQuery{q}
}

// FindAccountCartG retrieves a single record by ID.
func FindAccountCartG(ctx context.Context, cartID string, selectCols ...string) (*AccountCart, error) {
	return FindAccountCart(ctx, boil.GetContextDB(), cartID, selectCols...)
}

// FindAccountCart retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAccountCart(ctx context.Context, exec boil.ContextExecutor, cartID string, selectCols ...string) (*AccountCart, error) {
	accountCartObj := &AccountCart{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"account_carts\" where \"cart_id\"=$1", sel,
	)

	q := queries.Raw(query, cartID)

	err := q.Bind(ctx, exec, accountCartObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "orm: unable to select from account_carts")
	}

	if err = accountCartObj.doAfterSelectHooks(ctx, exec); err != nil {
		return accountCartObj, err
	}

	return accountCartObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *AccountCart) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AccountCart) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("orm: no account_carts provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accountCartColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	accountCartInsertCacheMut.RLock()
	cache, cached := accountCartInsertCache[key]
	accountCartInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			accountCartAllColumns,
			accountCartColumnsWithDefault,
			accountCartColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(accountCartType, accountCartMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(accountCartType, accountCartMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"account_carts\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"account_carts\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "orm: unable to insert into account_carts")
	}

	if !cached {
		accountCartInsertCacheMut.Lock()
		accountCartInsertCache[key] = cache
		accountCartInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single AccountCart record using the global executor.
// See Update for more documentation.
func (o *AccountCart) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the AccountCart.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AccountCart) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	accountCartUpdateCacheMut.RLock()
	cache, cached := accountCartUpdateCache[key]
	accountCartUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			accountCartAllColumns,
			accountCartPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("orm: unable to update account_carts, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"account_carts\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, accountCartPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(accountCartType, accountCartMapping, append(wl, accountCartPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update account_carts row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by update for account_carts")
	}

	if !cached {
		accountCartUpdateCacheMut.Lock()
		accountCartUpdateCache[key] = cache
		accountCartUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q accountCartQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q accountCartQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update all for account_carts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to retrieve rows affected for account_carts")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o AccountCartSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AccountCartSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("orm: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountCartPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"account_carts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, accountCartPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update all in accountCart slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to retrieve rows affected all in update all accountCart")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *AccountCart) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AccountCart) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("orm: no account_carts provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accountCartColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	accountCartUpsertCacheMut.RLock()
	cache, cached := accountCartUpsertCache[key]
	accountCartUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			accountCartAllColumns,
			accountCartColumnsWithDefault,
			accountCartColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			accountCartAllColumns,
			accountCartPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("orm: unable to upsert account_carts, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(accountCartPrimaryKeyColumns))
			copy(conflict, accountCartPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"account_carts\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(accountCartType, accountCartMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(accountCartType, accountCartMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "orm: unable to upsert account_carts")
	}

	if !cached {
		accountCartUpsertCacheMut.Lock()
		accountCartUpsertCache[key] = cache
		accountCartUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single AccountCart record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *AccountCart) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single AccountCart record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AccountCart) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("orm: no AccountCart provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), accountCartPrimaryKeyMapping)
	sql := "DELETE FROM \"account_carts\" WHERE \"cart_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete from account_carts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by delete for account_carts")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q accountCartQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q accountCartQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("orm: no accountCartQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete all from account_carts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by deleteall for account_carts")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o AccountCartSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AccountCartSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(accountCartBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountCartPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"account_carts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountCartPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete all from accountCart slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by deleteall for account_carts")
	}

	if len(accountCartAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *AccountCart) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("orm: no AccountCart provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AccountCart) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAccountCart(ctx, exec, o.CartID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AccountCartSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("orm: empty AccountCartSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AccountCartSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AccountCartSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountCartPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"account_carts\".* FROM \"account_carts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountCartPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "orm: unable to reload all in AccountCartSlice")
	}

	*o = slice

	return nil
}

// AccountCartExistsG checks if the AccountCart row exists.
func AccountCartExistsG(ctx context.Context, cartID string) (bool, error) {
	return AccountCartExists(ctx, boil.GetContextDB(), cartID)
}

// AccountCartExists checks if the AccountCart row exists.
func AccountCartExists(ctx context.Context, exec boil.ContextExecutor, cartID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"account_carts\" where \"cart_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, cartID)
	}
	row := exec.QueryRowContext(ctx, sql, cartID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "orm: unable to check if account_carts exists")
	}

	return exists, nil
}

// Exists checks if the AccountCart row exists.
func (o *AccountCart) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AccountCartExists(ctx, exec, o.CartID)
}
