// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	AccountAdmins           string
	AccountCartJewelleries  string
	AccountFavourites       string
	AccountOrderAddresses   string
	AccountOrderJewelleries string
	AccountOrders           string
	AccountProfiles         string
	Accounts                string
	Categories              string
	Countries               string
	Currencies              string
	Faqs                    string
	Gems                    string
	Jewelleries             string
	Materials               string
}{
	AccountAdmins:           "account_admins",
	AccountCartJewelleries:  "account_cart_jewelleries",
	AccountFavourites:       "account_favourites",
	AccountOrderAddresses:   "account_order_addresses",
	AccountOrderJewelleries: "account_order_jewelleries",
	AccountOrders:           "account_orders",
	AccountProfiles:         "account_profiles",
	Accounts:                "accounts",
	Categories:              "categories",
	Countries:               "countries",
	Currencies:              "currencies",
	Faqs:                    "faqs",
	Gems:                    "gems",
	Jewelleries:             "jewelleries",
	Materials:               "materials",
}
