// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	. "burmese_jewellery/models"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Display the main page
	// (GET /api)
	GetApi(c *gin.Context)
	// List user
	// (GET /api/admin/account)
	GetApiAdminAccount(c *gin.Context)
	// Get user
	// (GET /api/admin/account/{account_id})
	GetApiAdminAccountAccountId(c *gin.Context, accountId ID)
	// Update user status
	// (PUT /api/admin/account/{account_id})
	PutApiAdminAccountAccountId(c *gin.Context, accountId ID)
	// List admin user
	// (GET /api/admin/account_admin)
	GetApiAdminAccountAdmin(c *gin.Context)

	// (POST /api/admin/account_admin)
	PostApiAdminAccountAdmin(c *gin.Context)
	// Delete admin user
	// (DELETE /api/admin/account_admin/{account_admins_id})
	DeleteApiAdminAccountAdminAccountAdminsId(c *gin.Context, accountAdminsId ID)
	// Get admin user
	// (GET /api/admin/account_admin/{account_admins_id})
	GetApiAdminAccountAdminAccountAdminsId(c *gin.Context, accountAdminsId ID)
	// Edit admin user
	// (PUT /api/admin/account_admin/{account_admins_id})
	PutApiAdminAccountAdminAccountAdminsId(c *gin.Context, accountAdminsId ID)

	// (POST /api/admin/jewellery)
	PostApiAdminJewellery(c *gin.Context)

	// (PUT /api/admin/jewellery/{jewellery_id})
	PutApiAdminJewelleryJewelleryId(c *gin.Context, jewelleryId ID)
	// Login as admin user
	// (POST /api/admin/login)
	PostApiAdminLogin(c *gin.Context)
	// Handle Google OAuth2 callback
	// (GET /api/auth/google/callback)
	GetApiAuthGoogleCallback(c *gin.Context, params GetApiAuthGoogleCallbackParams)
	// Initiate Google OAuth2 login
	// (GET /api/auth/google/login)
	GetApiAuthGoogleLogin(c *gin.Context)
	// Health Check
	// (GET /api/health_check)
	GetApiHealthCheck(c *gin.Context)

	// (GET /api/jewellery)
	GetApiJewellery(c *gin.Context, params GetApiJewelleryParams)

	// (GET /api/jewellery/{jewellery_id})
	GetApiJewelleryJewelleryId(c *gin.Context, jewelleryId ID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetApi operation middleware
func (siw *ServerInterfaceWrapper) GetApi(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApi(c)
}

// GetApiAdminAccount operation middleware
func (siw *ServerInterfaceWrapper) GetApiAdminAccount(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiAdminAccount(c)
}

// GetApiAdminAccountAccountId operation middleware
func (siw *ServerInterfaceWrapper) GetApiAdminAccountAccountId(c *gin.Context) {

	var err error

	// ------------- Path parameter "account_id" -------------
	var accountId ID

	err = runtime.BindStyledParameter("simple", false, "account_id", c.Param("account_id"), &accountId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter account_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiAdminAccountAccountId(c, accountId)
}

// PutApiAdminAccountAccountId operation middleware
func (siw *ServerInterfaceWrapper) PutApiAdminAccountAccountId(c *gin.Context) {

	var err error

	// ------------- Path parameter "account_id" -------------
	var accountId ID

	err = runtime.BindStyledParameter("simple", false, "account_id", c.Param("account_id"), &accountId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter account_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutApiAdminAccountAccountId(c, accountId)
}

// GetApiAdminAccountAdmin operation middleware
func (siw *ServerInterfaceWrapper) GetApiAdminAccountAdmin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiAdminAccountAdmin(c)
}

// PostApiAdminAccountAdmin operation middleware
func (siw *ServerInterfaceWrapper) PostApiAdminAccountAdmin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiAdminAccountAdmin(c)
}

// DeleteApiAdminAccountAdminAccountAdminsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiAdminAccountAdminAccountAdminsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "account_admins_id" -------------
	var accountAdminsId ID

	err = runtime.BindStyledParameter("simple", false, "account_admins_id", c.Param("account_admins_id"), &accountAdminsId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter account_admins_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteApiAdminAccountAdminAccountAdminsId(c, accountAdminsId)
}

// GetApiAdminAccountAdminAccountAdminsId operation middleware
func (siw *ServerInterfaceWrapper) GetApiAdminAccountAdminAccountAdminsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "account_admins_id" -------------
	var accountAdminsId ID

	err = runtime.BindStyledParameter("simple", false, "account_admins_id", c.Param("account_admins_id"), &accountAdminsId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter account_admins_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiAdminAccountAdminAccountAdminsId(c, accountAdminsId)
}

// PutApiAdminAccountAdminAccountAdminsId operation middleware
func (siw *ServerInterfaceWrapper) PutApiAdminAccountAdminAccountAdminsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "account_admins_id" -------------
	var accountAdminsId ID

	err = runtime.BindStyledParameter("simple", false, "account_admins_id", c.Param("account_admins_id"), &accountAdminsId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter account_admins_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutApiAdminAccountAdminAccountAdminsId(c, accountAdminsId)
}

// PostApiAdminJewellery operation middleware
func (siw *ServerInterfaceWrapper) PostApiAdminJewellery(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiAdminJewellery(c)
}

// PutApiAdminJewelleryJewelleryId operation middleware
func (siw *ServerInterfaceWrapper) PutApiAdminJewelleryJewelleryId(c *gin.Context) {

	var err error

	// ------------- Path parameter "jewellery_id" -------------
	var jewelleryId ID

	err = runtime.BindStyledParameter("simple", false, "jewellery_id", c.Param("jewellery_id"), &jewelleryId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter jewellery_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutApiAdminJewelleryJewelleryId(c, jewelleryId)
}

// PostApiAdminLogin operation middleware
func (siw *ServerInterfaceWrapper) PostApiAdminLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiAdminLogin(c)
}

// GetApiAuthGoogleCallback operation middleware
func (siw *ServerInterfaceWrapper) GetApiAuthGoogleCallback(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiAuthGoogleCallbackParams

	// ------------- Required query parameter "state" -------------

	if paramValue := c.Query("state"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument state is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "state", c.Request.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter state: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "code" -------------

	if paramValue := c.Query("code"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument code is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code", c.Request.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter code: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiAuthGoogleCallback(c, params)
}

// GetApiAuthGoogleLogin operation middleware
func (siw *ServerInterfaceWrapper) GetApiAuthGoogleLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiAuthGoogleLogin(c)
}

// GetApiHealthCheck operation middleware
func (siw *ServerInterfaceWrapper) GetApiHealthCheck(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiHealthCheck(c)
}

// GetApiJewellery operation middleware
func (siw *ServerInterfaceWrapper) GetApiJewellery(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiJewelleryParams

	// ------------- Required query parameter "offset" -------------

	if paramValue := c.Query("offset"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument offset is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "limit" -------------

	if paramValue := c.Query("limit"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument limit is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", c.Request.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "category_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "category_id", c.Request.URL.Query(), &params.CategoryId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter category_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "gem_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "gem_id", c.Request.URL.Query(), &params.GemId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gem_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "material_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "material_id", c.Request.URL.Query(), &params.MaterialId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter material_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", c.Request.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "is_published" -------------

	err = runtime.BindQueryParameter("form", true, false, "is_published", c.Request.URL.Query(), &params.IsPublished)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter is_published: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiJewellery(c, params)
}

// GetApiJewelleryJewelleryId operation middleware
func (siw *ServerInterfaceWrapper) GetApiJewelleryJewelleryId(c *gin.Context) {

	var err error

	// ------------- Path parameter "jewellery_id" -------------
	var jewelleryId ID

	err = runtime.BindStyledParameter("simple", false, "jewellery_id", c.Param("jewellery_id"), &jewelleryId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter jewellery_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiJewelleryJewelleryId(c, jewelleryId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api", wrapper.GetApi)
	router.GET(options.BaseURL+"/api/admin/account", wrapper.GetApiAdminAccount)
	router.GET(options.BaseURL+"/api/admin/account/:account_id", wrapper.GetApiAdminAccountAccountId)
	router.PUT(options.BaseURL+"/api/admin/account/:account_id", wrapper.PutApiAdminAccountAccountId)
	router.GET(options.BaseURL+"/api/admin/account_admin", wrapper.GetApiAdminAccountAdmin)
	router.POST(options.BaseURL+"/api/admin/account_admin", wrapper.PostApiAdminAccountAdmin)
	router.DELETE(options.BaseURL+"/api/admin/account_admin/:account_admins_id", wrapper.DeleteApiAdminAccountAdminAccountAdminsId)
	router.GET(options.BaseURL+"/api/admin/account_admin/:account_admins_id", wrapper.GetApiAdminAccountAdminAccountAdminsId)
	router.PUT(options.BaseURL+"/api/admin/account_admin/:account_admins_id", wrapper.PutApiAdminAccountAdminAccountAdminsId)
	router.POST(options.BaseURL+"/api/admin/jewellery", wrapper.PostApiAdminJewellery)
	router.PUT(options.BaseURL+"/api/admin/jewellery/:jewellery_id", wrapper.PutApiAdminJewelleryJewelleryId)
	router.POST(options.BaseURL+"/api/admin/login", wrapper.PostApiAdminLogin)
	router.GET(options.BaseURL+"/api/auth/google/callback", wrapper.GetApiAuthGoogleCallback)
	router.GET(options.BaseURL+"/api/auth/google/login", wrapper.GetApiAuthGoogleLogin)
	router.GET(options.BaseURL+"/api/health_check", wrapper.GetApiHealthCheck)
	router.GET(options.BaseURL+"/api/jewellery", wrapper.GetApiJewellery)
	router.GET(options.BaseURL+"/api/jewellery/:jewellery_id", wrapper.GetApiJewelleryJewelleryId)
}

type GetApiRequestObject struct {
}

type GetApiResponseObject interface {
	VisitGetApiResponse(w http.ResponseWriter) error
}

type GetApi200Response struct {
}

func (response GetApi200Response) VisitGetApiResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetApiAdminAccountRequestObject struct {
}

type GetApiAdminAccountResponseObject interface {
	VisitGetApiAdminAccountResponse(w http.ResponseWriter) error
}

type GetApiAdminAccount200JSONResponse []Account

func (response GetApiAdminAccount200JSONResponse) VisitGetApiAdminAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiAdminAccountAccountIdRequestObject struct {
	AccountId ID `json:"account_id"`
}

type GetApiAdminAccountAccountIdResponseObject interface {
	VisitGetApiAdminAccountAccountIdResponse(w http.ResponseWriter) error
}

type GetApiAdminAccountAccountId200JSONResponse Account

func (response GetApiAdminAccountAccountId200JSONResponse) VisitGetApiAdminAccountAccountIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutApiAdminAccountAccountIdRequestObject struct {
	AccountId ID `json:"account_id"`
	Body      *PutApiAdminAccountAccountIdJSONRequestBody
}

type PutApiAdminAccountAccountIdResponseObject interface {
	VisitPutApiAdminAccountAccountIdResponse(w http.ResponseWriter) error
}

type PutApiAdminAccountAccountId200Response struct {
}

func (response PutApiAdminAccountAccountId200Response) VisitPutApiAdminAccountAccountIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetApiAdminAccountAdminRequestObject struct {
}

type GetApiAdminAccountAdminResponseObject interface {
	VisitGetApiAdminAccountAdminResponse(w http.ResponseWriter) error
}

type GetApiAdminAccountAdmin200JSONResponse []AccountAdmin

func (response GetApiAdminAccountAdmin200JSONResponse) VisitGetApiAdminAccountAdminResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiAdminAccountAdminRequestObject struct {
	Body *PostApiAdminAccountAdminJSONRequestBody
}

type PostApiAdminAccountAdminResponseObject interface {
	VisitPostApiAdminAccountAdminResponse(w http.ResponseWriter) error
}

type PostApiAdminAccountAdmin200Response struct {
}

func (response PostApiAdminAccountAdmin200Response) VisitPostApiAdminAccountAdminResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type DeleteApiAdminAccountAdminAccountAdminsIdRequestObject struct {
	AccountAdminsId ID `json:"account_admins_id"`
}

type DeleteApiAdminAccountAdminAccountAdminsIdResponseObject interface {
	VisitDeleteApiAdminAccountAdminAccountAdminsIdResponse(w http.ResponseWriter) error
}

type DeleteApiAdminAccountAdminAccountAdminsId204Response struct {
}

func (response DeleteApiAdminAccountAdminAccountAdminsId204Response) VisitDeleteApiAdminAccountAdminAccountAdminsIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetApiAdminAccountAdminAccountAdminsIdRequestObject struct {
	AccountAdminsId ID `json:"account_admins_id"`
}

type GetApiAdminAccountAdminAccountAdminsIdResponseObject interface {
	VisitGetApiAdminAccountAdminAccountAdminsIdResponse(w http.ResponseWriter) error
}

type GetApiAdminAccountAdminAccountAdminsId200JSONResponse AccountAdmin

func (response GetApiAdminAccountAdminAccountAdminsId200JSONResponse) VisitGetApiAdminAccountAdminAccountAdminsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutApiAdminAccountAdminAccountAdminsIdRequestObject struct {
	AccountAdminsId ID `json:"account_admins_id"`
	Body            *PutApiAdminAccountAdminAccountAdminsIdJSONRequestBody
}

type PutApiAdminAccountAdminAccountAdminsIdResponseObject interface {
	VisitPutApiAdminAccountAdminAccountAdminsIdResponse(w http.ResponseWriter) error
}

type PutApiAdminAccountAdminAccountAdminsId200Response struct {
}

func (response PutApiAdminAccountAdminAccountAdminsId200Response) VisitPutApiAdminAccountAdminAccountAdminsIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PostApiAdminJewelleryRequestObject struct {
	Body *PostApiAdminJewelleryJSONRequestBody
}

type PostApiAdminJewelleryResponseObject interface {
	VisitPostApiAdminJewelleryResponse(w http.ResponseWriter) error
}

type PostApiAdminJewellery200Response struct {
}

func (response PostApiAdminJewellery200Response) VisitPostApiAdminJewelleryResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PutApiAdminJewelleryJewelleryIdRequestObject struct {
	JewelleryId ID `json:"jewellery_id"`
	Body        *PutApiAdminJewelleryJewelleryIdJSONRequestBody
}

type PutApiAdminJewelleryJewelleryIdResponseObject interface {
	VisitPutApiAdminJewelleryJewelleryIdResponse(w http.ResponseWriter) error
}

type PutApiAdminJewelleryJewelleryId200Response struct {
}

func (response PutApiAdminJewelleryJewelleryId200Response) VisitPutApiAdminJewelleryJewelleryIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PostApiAdminLoginRequestObject struct {
	Body *PostApiAdminLoginJSONRequestBody
}

type PostApiAdminLoginResponseObject interface {
	VisitPostApiAdminLoginResponse(w http.ResponseWriter) error
}

type PostApiAdminLogin200JSONResponse struct {
	Token *string `json:"token,omitempty"`
}

func (response PostApiAdminLogin200JSONResponse) VisitPostApiAdminLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiAuthGoogleCallbackRequestObject struct {
	Params GetApiAuthGoogleCallbackParams
}

type GetApiAuthGoogleCallbackResponseObject interface {
	VisitGetApiAuthGoogleCallbackResponse(w http.ResponseWriter) error
}

type GetApiAuthGoogleCallback200JSONResponse AuthGoogleCallbackResp

func (response GetApiAuthGoogleCallback200JSONResponse) VisitGetApiAuthGoogleCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiAuthGoogleLoginRequestObject struct {
}

type GetApiAuthGoogleLoginResponseObject interface {
	VisitGetApiAuthGoogleLoginResponse(w http.ResponseWriter) error
}

type GetApiAuthGoogleLogin302Response struct {
}

func (response GetApiAuthGoogleLogin302Response) VisitGetApiAuthGoogleLoginResponse(w http.ResponseWriter) error {
	w.WriteHeader(302)
	return nil
}

type GetApiHealthCheckRequestObject struct {
}

type GetApiHealthCheckResponseObject interface {
	VisitGetApiHealthCheckResponse(w http.ResponseWriter) error
}

type GetApiHealthCheck200JSONResponse struct {
	Message string `json:"message"`
}

func (response GetApiHealthCheck200JSONResponse) VisitGetApiHealthCheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiJewelleryRequestObject struct {
	Params GetApiJewelleryParams
}

type GetApiJewelleryResponseObject interface {
	VisitGetApiJewelleryResponse(w http.ResponseWriter) error
}

type GetApiJewellery200JSONResponse []Jewellery

func (response GetApiJewellery200JSONResponse) VisitGetApiJewelleryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiJewelleryJewelleryIdRequestObject struct {
	JewelleryId ID `json:"jewellery_id"`
}

type GetApiJewelleryJewelleryIdResponseObject interface {
	VisitGetApiJewelleryJewelleryIdResponse(w http.ResponseWriter) error
}

type GetApiJewelleryJewelleryId200JSONResponse Jewellery

func (response GetApiJewelleryJewelleryId200JSONResponse) VisitGetApiJewelleryJewelleryIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Display the main page
	// (GET /api)
	GetApi(ctx context.Context, request GetApiRequestObject) (GetApiResponseObject, error)
	// List user
	// (GET /api/admin/account)
	GetApiAdminAccount(ctx context.Context, request GetApiAdminAccountRequestObject) (GetApiAdminAccountResponseObject, error)
	// Get user
	// (GET /api/admin/account/{account_id})
	GetApiAdminAccountAccountId(ctx context.Context, request GetApiAdminAccountAccountIdRequestObject) (GetApiAdminAccountAccountIdResponseObject, error)
	// Update user status
	// (PUT /api/admin/account/{account_id})
	PutApiAdminAccountAccountId(ctx context.Context, request PutApiAdminAccountAccountIdRequestObject) (PutApiAdminAccountAccountIdResponseObject, error)
	// List admin user
	// (GET /api/admin/account_admin)
	GetApiAdminAccountAdmin(ctx context.Context, request GetApiAdminAccountAdminRequestObject) (GetApiAdminAccountAdminResponseObject, error)

	// (POST /api/admin/account_admin)
	PostApiAdminAccountAdmin(ctx context.Context, request PostApiAdminAccountAdminRequestObject) (PostApiAdminAccountAdminResponseObject, error)
	// Delete admin user
	// (DELETE /api/admin/account_admin/{account_admins_id})
	DeleteApiAdminAccountAdminAccountAdminsId(ctx context.Context, request DeleteApiAdminAccountAdminAccountAdminsIdRequestObject) (DeleteApiAdminAccountAdminAccountAdminsIdResponseObject, error)
	// Get admin user
	// (GET /api/admin/account_admin/{account_admins_id})
	GetApiAdminAccountAdminAccountAdminsId(ctx context.Context, request GetApiAdminAccountAdminAccountAdminsIdRequestObject) (GetApiAdminAccountAdminAccountAdminsIdResponseObject, error)
	// Edit admin user
	// (PUT /api/admin/account_admin/{account_admins_id})
	PutApiAdminAccountAdminAccountAdminsId(ctx context.Context, request PutApiAdminAccountAdminAccountAdminsIdRequestObject) (PutApiAdminAccountAdminAccountAdminsIdResponseObject, error)

	// (POST /api/admin/jewellery)
	PostApiAdminJewellery(ctx context.Context, request PostApiAdminJewelleryRequestObject) (PostApiAdminJewelleryResponseObject, error)

	// (PUT /api/admin/jewellery/{jewellery_id})
	PutApiAdminJewelleryJewelleryId(ctx context.Context, request PutApiAdminJewelleryJewelleryIdRequestObject) (PutApiAdminJewelleryJewelleryIdResponseObject, error)
	// Login as admin user
	// (POST /api/admin/login)
	PostApiAdminLogin(ctx context.Context, request PostApiAdminLoginRequestObject) (PostApiAdminLoginResponseObject, error)
	// Handle Google OAuth2 callback
	// (GET /api/auth/google/callback)
	GetApiAuthGoogleCallback(ctx context.Context, request GetApiAuthGoogleCallbackRequestObject) (GetApiAuthGoogleCallbackResponseObject, error)
	// Initiate Google OAuth2 login
	// (GET /api/auth/google/login)
	GetApiAuthGoogleLogin(ctx context.Context, request GetApiAuthGoogleLoginRequestObject) (GetApiAuthGoogleLoginResponseObject, error)
	// Health Check
	// (GET /api/health_check)
	GetApiHealthCheck(ctx context.Context, request GetApiHealthCheckRequestObject) (GetApiHealthCheckResponseObject, error)

	// (GET /api/jewellery)
	GetApiJewellery(ctx context.Context, request GetApiJewelleryRequestObject) (GetApiJewelleryResponseObject, error)

	// (GET /api/jewellery/{jewellery_id})
	GetApiJewelleryJewelleryId(ctx context.Context, request GetApiJewelleryJewelleryIdRequestObject) (GetApiJewelleryJewelleryIdResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetApi operation middleware
func (sh *strictHandler) GetApi(ctx *gin.Context) {
	var request GetApiRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApi(ctx, request.(GetApiRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApi")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiResponseObject); ok {
		if err := validResponse.VisitGetApiResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiAdminAccount operation middleware
func (sh *strictHandler) GetApiAdminAccount(ctx *gin.Context) {
	var request GetApiAdminAccountRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiAdminAccount(ctx, request.(GetApiAdminAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiAdminAccount")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiAdminAccountResponseObject); ok {
		if err := validResponse.VisitGetApiAdminAccountResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiAdminAccountAccountId operation middleware
func (sh *strictHandler) GetApiAdminAccountAccountId(ctx *gin.Context, accountId ID) {
	var request GetApiAdminAccountAccountIdRequestObject

	request.AccountId = accountId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiAdminAccountAccountId(ctx, request.(GetApiAdminAccountAccountIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiAdminAccountAccountId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiAdminAccountAccountIdResponseObject); ok {
		if err := validResponse.VisitGetApiAdminAccountAccountIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutApiAdminAccountAccountId operation middleware
func (sh *strictHandler) PutApiAdminAccountAccountId(ctx *gin.Context, accountId ID) {
	var request PutApiAdminAccountAccountIdRequestObject

	request.AccountId = accountId

	var body PutApiAdminAccountAccountIdJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutApiAdminAccountAccountId(ctx, request.(PutApiAdminAccountAccountIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutApiAdminAccountAccountId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PutApiAdminAccountAccountIdResponseObject); ok {
		if err := validResponse.VisitPutApiAdminAccountAccountIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiAdminAccountAdmin operation middleware
func (sh *strictHandler) GetApiAdminAccountAdmin(ctx *gin.Context) {
	var request GetApiAdminAccountAdminRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiAdminAccountAdmin(ctx, request.(GetApiAdminAccountAdminRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiAdminAccountAdmin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiAdminAccountAdminResponseObject); ok {
		if err := validResponse.VisitGetApiAdminAccountAdminResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiAdminAccountAdmin operation middleware
func (sh *strictHandler) PostApiAdminAccountAdmin(ctx *gin.Context) {
	var request PostApiAdminAccountAdminRequestObject

	var body PostApiAdminAccountAdminJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiAdminAccountAdmin(ctx, request.(PostApiAdminAccountAdminRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiAdminAccountAdmin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostApiAdminAccountAdminResponseObject); ok {
		if err := validResponse.VisitPostApiAdminAccountAdminResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteApiAdminAccountAdminAccountAdminsId operation middleware
func (sh *strictHandler) DeleteApiAdminAccountAdminAccountAdminsId(ctx *gin.Context, accountAdminsId ID) {
	var request DeleteApiAdminAccountAdminAccountAdminsIdRequestObject

	request.AccountAdminsId = accountAdminsId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteApiAdminAccountAdminAccountAdminsId(ctx, request.(DeleteApiAdminAccountAdminAccountAdminsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteApiAdminAccountAdminAccountAdminsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteApiAdminAccountAdminAccountAdminsIdResponseObject); ok {
		if err := validResponse.VisitDeleteApiAdminAccountAdminAccountAdminsIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiAdminAccountAdminAccountAdminsId operation middleware
func (sh *strictHandler) GetApiAdminAccountAdminAccountAdminsId(ctx *gin.Context, accountAdminsId ID) {
	var request GetApiAdminAccountAdminAccountAdminsIdRequestObject

	request.AccountAdminsId = accountAdminsId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiAdminAccountAdminAccountAdminsId(ctx, request.(GetApiAdminAccountAdminAccountAdminsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiAdminAccountAdminAccountAdminsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiAdminAccountAdminAccountAdminsIdResponseObject); ok {
		if err := validResponse.VisitGetApiAdminAccountAdminAccountAdminsIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutApiAdminAccountAdminAccountAdminsId operation middleware
func (sh *strictHandler) PutApiAdminAccountAdminAccountAdminsId(ctx *gin.Context, accountAdminsId ID) {
	var request PutApiAdminAccountAdminAccountAdminsIdRequestObject

	request.AccountAdminsId = accountAdminsId

	var body PutApiAdminAccountAdminAccountAdminsIdJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutApiAdminAccountAdminAccountAdminsId(ctx, request.(PutApiAdminAccountAdminAccountAdminsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutApiAdminAccountAdminAccountAdminsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PutApiAdminAccountAdminAccountAdminsIdResponseObject); ok {
		if err := validResponse.VisitPutApiAdminAccountAdminAccountAdminsIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiAdminJewellery operation middleware
func (sh *strictHandler) PostApiAdminJewellery(ctx *gin.Context) {
	var request PostApiAdminJewelleryRequestObject

	var body PostApiAdminJewelleryJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiAdminJewellery(ctx, request.(PostApiAdminJewelleryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiAdminJewellery")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostApiAdminJewelleryResponseObject); ok {
		if err := validResponse.VisitPostApiAdminJewelleryResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutApiAdminJewelleryJewelleryId operation middleware
func (sh *strictHandler) PutApiAdminJewelleryJewelleryId(ctx *gin.Context, jewelleryId ID) {
	var request PutApiAdminJewelleryJewelleryIdRequestObject

	request.JewelleryId = jewelleryId

	var body PutApiAdminJewelleryJewelleryIdJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutApiAdminJewelleryJewelleryId(ctx, request.(PutApiAdminJewelleryJewelleryIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutApiAdminJewelleryJewelleryId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PutApiAdminJewelleryJewelleryIdResponseObject); ok {
		if err := validResponse.VisitPutApiAdminJewelleryJewelleryIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiAdminLogin operation middleware
func (sh *strictHandler) PostApiAdminLogin(ctx *gin.Context) {
	var request PostApiAdminLoginRequestObject

	var body PostApiAdminLoginJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiAdminLogin(ctx, request.(PostApiAdminLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiAdminLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostApiAdminLoginResponseObject); ok {
		if err := validResponse.VisitPostApiAdminLoginResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiAuthGoogleCallback operation middleware
func (sh *strictHandler) GetApiAuthGoogleCallback(ctx *gin.Context, params GetApiAuthGoogleCallbackParams) {
	var request GetApiAuthGoogleCallbackRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiAuthGoogleCallback(ctx, request.(GetApiAuthGoogleCallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiAuthGoogleCallback")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiAuthGoogleCallbackResponseObject); ok {
		if err := validResponse.VisitGetApiAuthGoogleCallbackResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiAuthGoogleLogin operation middleware
func (sh *strictHandler) GetApiAuthGoogleLogin(ctx *gin.Context) {
	var request GetApiAuthGoogleLoginRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiAuthGoogleLogin(ctx, request.(GetApiAuthGoogleLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiAuthGoogleLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiAuthGoogleLoginResponseObject); ok {
		if err := validResponse.VisitGetApiAuthGoogleLoginResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiHealthCheck operation middleware
func (sh *strictHandler) GetApiHealthCheck(ctx *gin.Context) {
	var request GetApiHealthCheckRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiHealthCheck(ctx, request.(GetApiHealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiHealthCheck")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiHealthCheckResponseObject); ok {
		if err := validResponse.VisitGetApiHealthCheckResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiJewellery operation middleware
func (sh *strictHandler) GetApiJewellery(ctx *gin.Context, params GetApiJewelleryParams) {
	var request GetApiJewelleryRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiJewellery(ctx, request.(GetApiJewelleryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiJewellery")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiJewelleryResponseObject); ok {
		if err := validResponse.VisitGetApiJewelleryResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiJewelleryJewelleryId operation middleware
func (sh *strictHandler) GetApiJewelleryJewelleryId(ctx *gin.Context, jewelleryId ID) {
	var request GetApiJewelleryJewelleryIdRequestObject

	request.JewelleryId = jewelleryId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiJewelleryJewelleryId(ctx, request.(GetApiJewelleryJewelleryIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiJewelleryJewelleryId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiJewelleryJewelleryIdResponseObject); ok {
		if err := validResponse.VisitGetApiJewelleryJewelleryIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW/juBH+KwJ7n1rZkp34JQYWbXrZ23UvdxfctuiHNjBoaSQzEUktSSVrBP7vBUlb",
	"lizZli+rXLaXYLORpeFw5pmZh/RQTyjgNOUMmJJo8oRksACKzeVlEPCMKX2ZCp6CUATMA2wfzEioP8EX",
	"TNME0ASdRXg8iIbnncGoN+qcD4b9zvwsCjr94GJ4Fg2HOMJD5KKIC4oVmqAsIyFykVqmerRUgrAYrdxc",
	"v1RYZWZGYBlFk/+gFFiohbSMIg+AXJTw4B60mhDMPawgRLduwaxclOIv18BitUCT/mBQM3EgQA+fYVV2",
	"rO/3/Y7f6/g9x/cn5t9fzP9Fb0KsoKMIhTqXEh4TtgtYz+/1RsPR2fmg548GF775aWCmVWZvb7EBikmC",
	"XJQuONM2xJzHib6IcABzzu/LqGzEj85m5EpwKJDqb7G+3w04LWLQWKk1sqh17I/H4/HFxcVFg+FZGrYS",
	"qJWLBHzOiIBQQ1pI9BLqlRQtpU7JvNt8Dj6/g0Bp69eFdRlSwvZXF9aPW68xO4vgSSmXzF3kIqlwFJXz",
	"xt5qEKPyDNVa/sYquJUyeOE8zlNq7U5tGuyJ3G9P8WtdODdYYFpN9nbIBUv5yMVO5fxZ/xwfvgPdhlQ3",
	"Ko85e8Ol2uPr/2nJfXMhPCXrj4Y7+4NF+7mB2YfmJ2P+cThfeE+4h0gPZUemFh/M1ut7nCRzHNz/CjLd",
	"65C+/E5AhCboT952K+6t9+HeZhO+chGRMwExkQqMNQX8lcggN2XOeQKYVWwvD68zfXqltR7dOvwDHiFJ",
	"QCyrTgVYQczFsrVtS3vrewgyECRVhLOy6n9DqPPL+YELeADhEObcJFgRllHnkaiFg52POIk6ARFBAg6P",
	"nCuCKWehdJ1+t+9Q2qSuYqCtgUYojmGWiR2aXiiVyonnUQgJ7ioSRZgtNWN7RHpmjPdPe9N7H3A6VUCv",
	"+95arhNZOOaYhR09Uac3HIzOh2eDWc8/HwzOxrP3V7Ofundp/Nf/Zr7fH/J0lkn6rtcdDdxe13eHXd8+",
	"+C4QPP35nd/tufZ3rH/tsxAinCVqqq159zM3fy8fMEnwPIEpUyAYTqzoyQMiqt49wjythUzO0myeELlo",
	"VGouutsURWtRpFiBIDhpbQKGKRxM/UbrgyAB7HzLNd9q8+mjhGM1PN9aQJiCGIQe/TnDTBG13FVQGE7Y",
	"vsEvtJkuRdotUV5exuVoraEtc0zB2Q1qxUrdScHTdt85Qx/YjbZO1W+E+kaob4T67RLqa6C9w+SWvXHb",
	"G7d9i9z2xjynMM/vRTXaDvhik+CKB4ZZSoWPfiAsdHimHMoFOHiuLz894jg2AJsaMoUz8Txpb3cJNxnD",
	"Il5Vd3kz1fFxfiT3GQXKuxobokz8Nvecy5spctEDCGkH9bp+19c6eQoMp0RnUdfv9k3HSy2M1Z65/4Ri",
	"MFtjTZVYzzkN0QR9AHWZEqQxlyln0lJo3/erBv6ECXNSHIMTEpkmeAmhI7MgACmjLEmWJnQyoxSLJZqg",
	"KyvkqAU4dDNU+4RjabopaYpu9RBtn2faWF6hLXLAWtN727RG6i0POFNgFeE0TUhgdHh30lK27a/oK6KA",
	"yhPaMOsswULgpU2SMki//LgDwzWRysmkyYncddP/2+O897Q9eFqdgMT6zzQ0sReYggKhp3tCRFum82FT",
	"KpPy4da23ixnbeE5hMr0Cq1Wt8/EvxHsDWD+AHtRdlGa1SB4k70iBD9nINXfebj82uDtdFZXZXrVxq6a",
	"1H4F73+Z76AGcic/I2qU37ZjfUpir7vlL1bndsLfXOzGvwPJyGVdNnK53+/WsmPn0OqZ2XFC+LckZz7K",
	"DdeFkICCKjxX5n4dQMVreWLp5nN/bQ48r2JkPQh3F0lz91jKnFIorxIPv5XEbbwwHKvIhsvDa4K3ZUr4",
	"6uvF+5AciUOZLe5Kx0xHKXN7KtUOODU91VbJMnffeyq2XgxHHkvX3Nb8omGe7jR5Xl+KVps/rQbBvPPV",
	"LP/MWy4vsFYX3qZp7npjK8p9NMXvwQgcPcdvsjPShjtYNuSATC08+wqjF6wP0o/tGCsn79Wc37FRD+mb",
	"3Ss4uSRybWl8ziybrGvDSB0sigpKe+YLeHh8Oi100mytrrn1LzU0CftHzMIEHDva2SCwDdCeZkAh/HkR",
	"Nor9tg4LWJz5/SoD/AohERAoR/Ed88yMtltRdmbKiCI6WWrk9/qyAJyoxSxYwNEU/mhEvzeSX7WSKUip",
	"3TEgmKanjdXRd6fW424bVPynvBPkbCzfzQXjnrPxbwMXVwtdn1vESkv/AbiKa36l0Nde+vXlxaNIgmpS",
	"YIW2ZEHt2R69CaHkdLV1mswKfMKKu0dNuXv6fH15//X5qsod3OfrW/eADxJyLdLlk/bK+O0bVbcv0YPY",
	"ZnXzBkQ98xzaQzYpq995+9jSYlbAtymemsVAPNTvIq55gBMH2AMRnFEwHelS7z/RAgsu1WTsj0ZIO7fW",
	"XzkBWDd8Nl8b122oiliaFoTStEbkF8upW76zn1e3q/8FAAD//067FwfyMwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
