name: Go

on:
  push:
    tags:
      - v*
    branches:
      - master
      - dev
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          cache-dependency-path: subdir/go.sum
      - name: Display Go version
        run: go version
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
      - name: Install dependencies
        run: |
          go get .
      - name: Build
        run: go build -v ./...
      - name: Test with Go
        run: go test -json > TestResults-${{ matrix.go-version }}.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json
