// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package models

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Defines values for AccountAdminAccountAdminRole.
const (
	Admin AccountAdminAccountAdminRole = "admin"
	Staff AccountAdminAccountAdminRole = "staff"
)

// Defines values for AccountAdminAccountAdminStatus.
const (
	Active      AccountAdminAccountAdminStatus = "active"
	Deactivated AccountAdminAccountAdminStatus = "deactivated"
	Locked      AccountAdminAccountAdminStatus = "locked"
)

// AccountAdmin defines model for AccountAdmin.
type AccountAdmin struct {
	// AccountAdminId Account Admin ID
	AccountAdminId     AccountAdminID                 `json:"account_admin_id"`
	AccountAdminRole   AccountAdminAccountAdminRole   `db:"password" json:"account_admin_role"`
	AccountAdminStatus AccountAdminAccountAdminStatus `db:"account_admin_status" json:"account_admin_status"`
	Mail               openapi_types.Email            `db:"mail" json:"mail"`
}

// AccountAdminAccountAdminRole defines model for AccountAdmin.AccountAdminRole.
type AccountAdminAccountAdminRole string

// AccountAdminAccountAdminStatus defines model for AccountAdmin.AccountAdminStatus.
type AccountAdminAccountAdminStatus string

// AccountAdminID Account Admin ID
type AccountAdminID = openapi_types.UUID

// AccountAdminLoginParam defines model for AccountAdminLoginParam.
type AccountAdminLoginParam struct {
	Mail     openapi_types.Email `db:"mail" json:"mail"`
	Password string              `db:"password" json:"password"`
}

// ErrMsg Error Message
type ErrMsg struct {
	// Message Error Message
	Message *string `json:"message,omitempty"`

	// Version Application Version
	Version *string `json:"version,omitempty"`
}

// Jewellery defines model for Jewellery.
type Jewellery struct {
	Description *string `db:"description" json:"description,omitempty"`
	ImageUrl    *string `db:"image_url" json:"image_url,omitempty"`

	// JewelleryId Jewellery ID
	JewelleryId *JewelleryID `json:"jewellery_id,omitempty"`
	Name        *string      `db:"name" json:"name,omitempty"`
	Price       *int         `db:"price" json:"price,omitempty"`
	Quantity    *int64       `db:"quantity" json:"quantity,omitempty"`
}

// JewelleryID Jewellery ID
type JewelleryID = openapi_types.UUID

// JewelleryIDParam Jewellery ID
type JewelleryIDParam = JewelleryID

// GetApiAuthGoogleCallbackParams defines parameters for GetApiAuthGoogleCallback.
type GetApiAuthGoogleCallbackParams struct {
	// State OAuth2 state parameter
	State string `form:"state" json:"state"`

	// Code OAuth2 code parameter
	Code string `form:"code" json:"code"`
}

// PostApiAdminAccountAdminJSONRequestBody defines body for PostApiAdminAccountAdmin for application/json ContentType.
type PostApiAdminAccountAdminJSONRequestBody = AccountAdmin

// PutApiAdminAccountAdminAccountAdminsIdJSONRequestBody defines body for PutApiAdminAccountAdminAccountAdminsId for application/json ContentType.
type PutApiAdminAccountAdminAccountAdminsIdJSONRequestBody = AccountAdmin

// PostApiAdminLoginJSONRequestBody defines body for PostApiAdminLogin for application/json ContentType.
type PostApiAdminLoginJSONRequestBody = AccountAdminLoginParam

// GetApiJewelleryJSONRequestBody defines body for GetApiJewellery for application/json ContentType.
type GetApiJewelleryJSONRequestBody = Jewellery
